#!/usr/bin/env python3

# create a list called Dogs
Dogs = ["dog1", "dog2", "dog3"]
# display Dogs
print(Dogs)

# ammend the Cats list to the Dogs list (so that it is a single list)
Dogs.append(Cats)
print(Dogs)
