("ello")
("did you say, hello?")
("No, I said ell, but that\'s close enough")
("ello")
("did you say, hello?")
("No, I said ell, but that\'s close enough")
("ello")
("did you say, hello?")
("No, I said ell, but that\'s close enough")
("ello")
("did you say, hello?")
("No, I said ell, but that\'s close enough")
("ello")
("did you say, hello?")
("No, I said ell, but that\'s close enough")
("ello")
("did you say, hello?")
("No, I said ell, but that\'s close enough")
("ello")
("did you say, hello?")
("No, I said ell, but that\'s close enough")
("ello")
("did you say, hello?")
("No, I said ell, but that\'s close enough")
("ello")
("did you say, hello?")
("No, I said ell, but that\'s close enough")

